# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'v1.0.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(702, 489)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        # self.gv = QtWidgets.QGraphicsView(self.centralwidget)
        # self.gv.setObjectName("gv")
        # self.verticalLayout.addWidget(self.gv)
        self.hs = QtWidgets.QSlider(self.centralwidget)
        self.hs.setOrientation(QtCore.Qt.Horizontal)
        self.hs.setObjectName("hs")
        self.verticalLayout.addWidget(self.hs)
        self.lb1 = QtWidgets.QLabel(self.centralwidget)
        self.lb1.setText("")
        self.lb1.setObjectName("lb1")
        self.verticalLayout.addWidget(self.lb1)
        self.pb = QtWidgets.QPushButton(self.centralwidget)
        self.pb.setObjectName("pb")
        self.verticalLayout.addWidget(self.pb)
        self.lb2 = QtWidgets.QLabel(self.centralwidget)
        self.lb2.setText("")
        self.lb2.setObjectName("lb2")
        self.verticalLayout.addWidget(self.lb2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 702, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuEdici_n = QtWidgets.QMenu(self.menubar)
        self.menuEdici_n.setObjectName("menuEdici_n")
        self.menuInfo = QtWidgets.QMenu(self.menubar)
        self.menuInfo.setObjectName("menuInfo")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbrir = QtWidgets.QAction(MainWindow)
        self.actionAbrir.setObjectName("actionAbrir")
        self.actionGuardar = QtWidgets.QAction(MainWindow)
        self.actionGuardar.setObjectName("actionGuardar")
        self.actionSalir = QtWidgets.QAction(MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.actionAyuda = QtWidgets.QAction(MainWindow)
        self.actionAyuda.setObjectName("actionAyuda")
        self.actionInformacion = QtWidgets.QAction(MainWindow)
        self.actionInformacion.setObjectName("actionInformacion")
        self.menuMenu.addAction(self.actionAbrir)
        self.menuMenu.addAction(self.actionGuardar)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionSalir)
        self.menuInfo.addAction(self.actionAyuda)
        self.menuInfo.addAction(self.actionInformacion)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuEdici_n.menuAction())
        self.menubar.addAction(self.menuInfo.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CuantiGel"))
        self.pb.setText(_translate("MainWindow", "OK"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.menuEdici_n.setTitle(_translate("MainWindow", "Edición"))
        self.menuInfo.setTitle(_translate("MainWindow", "Info"))
        self.actionAbrir.setText(_translate("MainWindow", "Abrir"))
        self.actionGuardar.setText(_translate("MainWindow", "Guardar"))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))
        self.actionAyuda.setText(_translate("MainWindow", "Ayuda"))
        self.actionInformacion.setText(_translate("MainWindow", "Información"))
