from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(582, 393)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.hs = QtWidgets.QSlider(self.centralwidget)
        self.hs.setEnabled(False)
        self.hs.setOrientation(QtCore.Qt.Horizontal)
        self.hs.setObjectName("hs")
        self.horizontalLayout.addWidget(self.hs)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.lb1 = QtWidgets.QLabel(self.centralwidget)
        self.lb1.setText("")
        self.lb1.setObjectName("lb1")
        self.verticalLayout.addWidget(self.lb1)
        self.pb_calcular = QtWidgets.QPushButton(self.centralwidget)
        self.pb_calcular.setEnabled(False)
        self.pb_calcular.setObjectName("pb_calcular")
        self.verticalLayout.addWidget(self.pb_calcular)
        self.lb2 = QtWidgets.QLabel(self.centralwidget)
        self.lb2.setText("")
        self.lb2.setObjectName("lb2")
        self.verticalLayout.addWidget(self.lb2)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 582, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuEdici_n = QtWidgets.QMenu(self.menubar)
        self.menuEdici_n.setObjectName("menuEdici_n")
        self.menuInfo = QtWidgets.QMenu(self.menubar)
        self.menuInfo.setObjectName("menuInfo")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbrir = QtWidgets.QAction(MainWindow)
        self.actionAbrir.setObjectName("actionAbrir")
        self.actionGuardar = QtWidgets.QAction(MainWindow)
        self.actionGuardar.setObjectName("actionGuardar")
        self.actionSalir = QtWidgets.QAction(MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.actionAyuda = QtWidgets.QAction(MainWindow)
        self.actionAyuda.setObjectName("actionAyuda")
        self.actionInformacion = QtWidgets.QAction(MainWindow)
        self.actionInformacion.setObjectName("actionInformacion")
        self.actionSeparar_canales = QtWidgets.QAction(MainWindow)
        self.actionSeparar_canales.setEnabled(False)
        self.actionSeparar_canales.setObjectName("actionSeparar_canales")
        self.actionTransformar_a_escala_grises = QtWidgets.QAction(MainWindow)
        self.actionTransformar_a_escala_grises.setEnabled(False)
        self.actionTransformar_a_escala_grises.setObjectName("actionTransformar_a_escala_grises")
        self.actionHistograma = QtWidgets.QAction(MainWindow)
        self.actionHistograma.setObjectName("actionHistograma")
        self.actionHistograma_2 = QtWidgets.QAction(MainWindow)
        self.actionHistograma_2.setEnabled(False)
        self.actionHistograma_2.setObjectName("actionHistograma_2")
        self.actionGenerar_informe = QtWidgets.QAction(MainWindow)
        self.actionGenerar_informe.setEnabled(False)
        self.actionGenerar_informe.setObjectName("actionGenerar_informe")
        self.menuMenu.addAction(self.actionAbrir)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionSalir)
        self.menuEdici_n.addAction(self.actionTransformar_a_escala_grises)
        self.menuInfo.addAction(self.actionAyuda)
        self.menuInfo.addAction(self.actionInformacion)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuEdici_n.menuAction())
        self.menubar.addAction(self.menuInfo.menuAction())

        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icono.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CG 1.0"))
        self.pb_calcular.setText(_translate("MainWindow", "Calcular"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menú"))
        self.menuEdici_n.setTitle(_translate("MainWindow", "Edición"))
        self.menuInfo.setTitle(_translate("MainWindow", "Info"))
        self.actionAbrir.setText(_translate("MainWindow", "Abrir"))
        self.actionGuardar.setText(_translate("MainWindow", "Guardar"))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))
        self.actionAyuda.setText(_translate("MainWindow", "Ayuda"))
        self.actionInformacion.setText(_translate("MainWindow", "Información"))
        self.actionSeparar_canales.setText(_translate("MainWindow", "Separar canales"))
        self.actionTransformar_a_escala_grises.setText(_translate("MainWindow", "Transformar a escala grises"))
        self.actionHistograma.setText(_translate("MainWindow", "Histograma"))
        self.actionHistograma_2.setText(_translate("MainWindow", "Histograma"))
        self.actionGenerar_informe.setText(_translate("MainWindow", "Generar informe"))
